"""Write ``CITATION.cff`` from ``ampere._citation.CITATION``.

The dictionary in ``ampere/_citation.py`` is the one place the citation's
facts live; this script renders it in the Citation File Format 1.2.0, which
GitHub's "Cite this repository" button and Zenodo read. Run it from the
repository root after changing a fact there::

    pixi run python scripts/write_citation_cff.py

``tests/core/test_citation.py`` fails if the committed ``CITATION.cff`` is not
exactly what this script writes. Written by hand rather than through a YAML
library so the output is byte-stable and needs nothing beyond the standard
library.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from ampere._citation import CITATION, Citation  # noqa: E402

HEADER = """\
# This file is generated by scripts/write_citation_cff.py from
# ampere/_citation.py -- edit that dictionary and re-run the script, never this
# file (tests/core/test_citation.py checks the two agree).
"""


def _quote(value: str) -> str:
    # A JSON string is a valid YAML double-quoted scalar.
    return json.dumps(value, ensure_ascii=False)


def render(citation: Citation = CITATION) -> str:
    """The ``CITATION.cff`` text for ``citation``."""
    lines = [
        HEADER.rstrip("\n"),
        "cff-version: 1.2.0",
        f"message: {_quote(citation['message'])}",
        "type: software",
        f"title: {_quote(citation['title'])}",
        f"version: {_quote(citation['version'])}",
    ]
    if citation["date_released"]:
        lines.append(f"date-released: {_quote(citation['date_released'])}")
    else:
        lines.append("# date-released: filled on the day v1.0.0b1 is tagged")
    if citation["doi"]:
        lines.append(f"doi: {_quote(citation['doi'])}")
    else:
        lines.append("# doi: Zenodo mints it at the first GitHub release; added after it")
    lines += [
        f"license: {_quote(citation['license'])}",
        f"repository-code: {_quote(citation['repository_code'])}",
        f"url: {_quote(citation['url'])}",
        "authors:",
    ]
    for author in citation["authors"]:
        lines.append(f"  - family-names: {_quote(author['family_names'])}")
        lines.append(f"    given-names: {_quote(author['given_names'])}")
        if author["email"]:
            lines.append(f"    email: {_quote(author['email'])}")
    if citation["paper"]:
        lines.append(f"# The paper, once published: {citation['paper']}")
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write ``CITATION.cff`` at the repository root."""
    (ROOT / "CITATION.cff").write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
