"""Backend-neutral core contracts for ampere v2.

Everything in this package is pure numpy/scipy/astropy.units/stdlib. It never
imports torch, jax, paramax or any other optional dependency, lazily or
otherwise (``architecture.md`` §3-4), because it is the shared vocabulary the
reference, torch and jax backends all implement.

Currently landed: the parameter and prior contract (W1.3,
``docs/design/contracts/parameters.md``), the ModelResult schema (W1.4,
``docs/design/contracts/results_schema.md``), the transformation and
instrument contract (W1.5, ``docs/design/contracts/transformations.md``), the
likelihood/noise-model contract (W1.6,
``docs/design/contracts/likelihoods.md``) and the dataset, fitting-problem and
inference contract (W1.7, ``docs/design/contracts/inference.md``). The
remaining §4 contract — ``astropy_compat`` — arrives with Phase 4.
"""

from __future__ import annotations

from .dataset import (
    DEFAULT_FAILURE_HISTORY,
    INSTRUMENT_COMPONENT,
    LATENT_COMPONENT,
    LATENT_NAME,
    LIKELIHOOD_COMPONENT,
    MODEL_COMPONENT,
    SHARED_COMPONENT,
    Capabilities,
    Capable,
    Dataset,
    DatasetCollection,
    Evaluation,
    Failure,
    FailureReason,
    FittingProblem,
    Simulation,
    declared_capabilities,
)
from .exceptions import (
    AmpereError,
    CapabilityError,
    ChannelError,
    CompositionError,
    ContractError,
    DatasetError,
    LikelihoodError,
    LoweringError,
    OptionalDependencyError,
    ParameterError,
    SchemaError,
    TransformationError,
    TyingError,
)
from .likelihood import (
    DTYPE,
    CauchyFamily,
    Censoring,
    ComplexGaussianFamily,
    DenseGP,
    GaussianFamily,
    GaussianProcessNoise,
    GPConditional,
    GPSolver,
    IndependentNoise,
    InducingPointGP,
    Kernel,
    KernelSpec,
    LatentDeclaration,
    Likelihood,
    LikelihoodFamily,
    LimitKind,
    Marginalisation,
    Matern32,
    NoiseModel,
    NoiseParams,
    PoissonFamily,
    QuasisepGP,
    RiceFamily,
    SquaredExponential,
    StructuredGridGP,
    StudentTFamily,
    VecchiaGP,
    VonMisesFamily,
    WindowedSparseGP,
    family_named,
    latent_parameter,
    list_families,
    register_family,
)
from .parameter import (
    SEPARATOR,
    Bijection,
    Binding,
    Buffer,
    BufferSet,
    HierarchicalPrior,
    Identity,
    Log,
    Logit,
    Parameter,
    Parameterised,
    ParameterMapping,
    ParameterSet,
    Plate,
    PlateBinding,
    Prior,
    PriorSpec,
    Tie,
    default_bijection_for,
    describe_prior,
    log_density,
    prior_from_spec,
)
from .rng import (
    generator,
    substream,
)
from .results_schema import (
    DEFAULT_CHANNEL,
    REGULARITY_RTOL,
    AnomalyScore,
    Axis,
    AxisSpec,
    Cube,
    FunctionSamples,
    Image,
    Layout,
    ModelResult,
    Order,
    PhotometricPoints,
    Spectrum,
    TimeSeries,
    VisibilitySet,
)
from .transform import (
    COORDINATE_RTOL,
    AxisRequirement,
    ChannelRequirements,
    Instrument,
    Model,
    Transformation,
    negotiate,
    propagate_mask,
)

__all__ = [
    "COORDINATE_RTOL",
    "DEFAULT_CHANNEL",
    "DEFAULT_FAILURE_HISTORY",
    "DTYPE",
    "INSTRUMENT_COMPONENT",
    "LATENT_COMPONENT",
    "LATENT_NAME",
    "LIKELIHOOD_COMPONENT",
    "MODEL_COMPONENT",
    "REGULARITY_RTOL",
    "SEPARATOR",
    "SHARED_COMPONENT",
    "AmpereError",
    "AnomalyScore",
    "Axis",
    "AxisRequirement",
    "AxisSpec",
    "Bijection",
    "Binding",
    "Buffer",
    "BufferSet",
    "Capabilities",
    "CapabilityError",
    "Capable",
    "CauchyFamily",
    "Censoring",
    "ChannelError",
    "ChannelRequirements",
    "ComplexGaussianFamily",
    "CompositionError",
    "ContractError",
    "Cube",
    "Dataset",
    "DatasetCollection",
    "DatasetError",
    "DenseGP",
    "Evaluation",
    "Failure",
    "FailureReason",
    "FittingProblem",
    "FunctionSamples",
    "GPConditional",
    "GPSolver",
    "GaussianFamily",
    "GaussianProcessNoise",
    "HierarchicalPrior",
    "Identity",
    "Image",
    "IndependentNoise",
    "InducingPointGP",
    "Instrument",
    "Kernel",
    "KernelSpec",
    "LatentDeclaration",
    "Layout",
    "Likelihood",
    "LikelihoodError",
    "LikelihoodFamily",
    "LimitKind",
    "Log",
    "Logit",
    "LoweringError",
    "Marginalisation",
    "Matern32",
    "Model",
    "ModelResult",
    "NoiseModel",
    "NoiseParams",
    "OptionalDependencyError",
    "Order",
    "Parameter",
    "ParameterError",
    "ParameterMapping",
    "ParameterSet",
    "Parameterised",
    "PhotometricPoints",
    "Plate",
    "PlateBinding",
    "PoissonFamily",
    "Prior",
    "PriorSpec",
    "QuasisepGP",
    "RiceFamily",
    "SchemaError",
    "Simulation",
    "Spectrum",
    "SquaredExponential",
    "StructuredGridGP",
    "StudentTFamily",
    "Tie",
    "TimeSeries",
    "Transformation",
    "TransformationError",
    "TyingError",
    "VecchiaGP",
    "VisibilitySet",
    "VonMisesFamily",
    "WindowedSparseGP",
    "declared_capabilities",
    "default_bijection_for",
    "describe_prior",
    "family_named",
    "generator",
    "latent_parameter",
    "list_families",
    "log_density",
    "negotiate",
    "prior_from_spec",
    "propagate_mask",
    "register_family",
    "substream",
]
