r"""Equispaced Fourier features: the second reduced-rank spectral solver (**W5.6**).

``DEVELOPMENT_PLAN.md`` §5's Phase 5 rule is that an approximate solver is
**chosen by measurement**, and W5.6 is that measurement: EFGP and Vecchia
(:mod:`ampere.core.vecchia`) implemented far enough to benchmark against W5.4's
:class:`~ampere.core.HilbertSpaceGP` and against :class:`~ampere.core.DenseGP`
on an image. This module is the EFGP half. It is a **reference-only
prototype**: numpy and scipy, no torch or jax twin, and it is not one of the
declared strategy slots of ``likelihoods.md`` §7 — the bake-off's decision-log
row says which of the two is promoted to a full three-backend solver.

The method
----------
Greengard, Rachh & Barnett (2023), *Equispaced Fourier representations for
efficient Gaussian process regression from a billion data points*. Bochner's
theorem writes a stationary kernel as the inverse transform of its spectral
density; ampere's convention (:meth:`~ampere.core.kernels.Kernel.spectral_density`)
is

.. math::
    k(\mathbf r) = (2\pi)^{-d} \int S(\|\boldsymbol\omega\|)\,
    e^{i \boldsymbol\omega \cdot \mathbf r}\, \mathrm d^d \boldsymbol\omega .

Discretise that integral on an **equispaced** frequency grid
:math:`\boldsymbol\omega_{\mathbf j} = (h_1 j_1, \ldots, h_d j_d)`,
:math:`j_k \in \{-M_k, \ldots, M_k\}`, by the rectangle rule:

.. math::
    k(\mathbf r) \;\approx\; \sum_{\mathbf j} w_{\mathbf j}\,
    e^{i \boldsymbol\omega_{\mathbf j} \cdot \mathbf r},
    \qquad
    w_{\mathbf j} = \frac{\prod_k h_k}{(2\pi)^d}\,
        S\big(\|\boldsymbol\omega_{\mathbf j}\|\big) \; \ge 0 ,

so that with :math:`\tilde\Phi_{p\mathbf j} = \sqrt{w_{\mathbf j}}\,
e^{i\boldsymbol\omega_{\mathbf j}\cdot \mathbf x_p}` the covariance is
:math:`K \approx \tilde\Phi \tilde\Phi^{\mathsf H}` — a rank-``m``
factorisation, exactly as HSGP's is, and every quantity follows from the same
Woodbury identity on :math:`M = I_m + \tilde\Phi^{\mathsf H} D^{-1}
\tilde\Phi`.

**Why bother, when HSGP already factorises the covariance that way.** Because
the grid is equispaced, and that is the whole method:

.. math::
    \big(\tilde\Phi^{\mathsf H} D^{-1} \tilde\Phi\big)_{\mathbf j \mathbf k}
    = \sqrt{w_{\mathbf j} w_{\mathbf k}}
      \sum_p \frac{e^{-i (\boldsymbol\omega_{\mathbf j} -
      \boldsymbol\omega_{\mathbf k})\cdot \mathbf x_p}}{D_p}
    = \sqrt{w_{\mathbf j} w_{\mathbf k}}\; G[\mathbf j - \mathbf k] ,

which depends on the index **difference** alone. The normal matrix is
therefore (block-)Toeplitz, generated by one array :math:`G` on the difference
grid, and three costs collapse at once:

* :math:`G` is a *separable* sum — :math:`e^{-i h\boldsymbol\delta \cdot
  \mathbf x} = \prod_k e^{-i h_k \delta_k x_k}` — so it is assembled by one
  complex GEMM per axis pair at :math:`O(N\,2^d m)` rather than by forming
  :math:`\tilde\Phi^{\mathsf H} D^{-1}\tilde\Phi` at :math:`O(N m^2)`. **That
  factor of** :math:`m/2^d` **is the measured win over HSGP**, and at image
  scale it is two orders of magnitude.
* the ``(N, m)`` block is never formed for the marginal likelihood, so the
  memory is :math:`O(N m^{1/d} d + m^2)` rather than :math:`O(N m)`;
* the Toeplitz matrix multiplies a vector by FFT in :math:`O(m \log m)`
  (:func:`toeplitz_matvec`), so a *solve* need not be a factorisation.

What the FFT does **not** give, and what W5.6 measures
------------------------------------------------------
Greengard et al.'s target is the posterior mean, which is a linear solve, and
for that the story ends at :math:`O(N + m\log m)`: conjugate gradients on a
matrix that is :math:`I` plus something positive semi-definite converges in a
handful of iterations, each an FFT (:func:`solve_iterative`). A **marginal
likelihood** needs :math:`\log|M|` as well, and a Toeplitz determinant has no
FFT: the honest options are an :math:`O(m^3)` Cholesky or a stochastic
Lanczos-quadrature estimate, and a stochastic log-determinant inside an MCMC
likelihood is a noisy target rather than a cheap one. This solver therefore
factorises :math:`M` with a Cholesky and says so; :func:`solve_iterative` is
supplied beside it so the bake-off can measure what the iterative route does
and does not remove. See ``docs/design/contracts/likelihoods.md`` §7's
bake-off subsection for the measured numbers.

The approximation's two parameters
----------------------------------
The same two HSGP has, meaning the same things, so the two are comparable at a
glance:

``basis_size``
    Grid points **per axis**, and odd, because the grid is symmetric about
    :math:`\boldsymbol\omega = 0`. The total ``m`` is their product. It sets
    the truncation: the grid reaches :math:`M_k h_k`, and what is cut off is
    the tail of :math:`S` beyond it.
``boundary_factor``
    The spacing, through :math:`h_k = \pi / (c\,S_k)` for a data half-extent
    :math:`S_k`. Poisson summation makes the rectangle rule's error *exactly*
    the periodisation :math:`\sum_{n \ne 0} k(\mathbf r + 2\pi \mathbf n / h)`,
    so :math:`2\pi/h_k = 2 c S_k` must exceed the data's own diameter
    :math:`2 S_k` with room for the kernel to decay — which is ``c > 1``, the
    identical statement to HSGP's box needing to contain the data with room to
    spare. Refining one of the two alone converges to the wrong answer, as
    ``likelihoods.md`` §7's measured sweep shows for HSGP.

Both are dataclass fields, so they enter ``Likelihood.to_spec``'s hash
(W5.4's correction to fold-in 10: an approximation changes the likelihood's
value, so it is a declaration and not configuration), and both are repeated in
:meth:`EquispacedFourierGP.provenance_config`.
"""

from __future__ import annotations

import dataclasses
import math
from collections.abc import Mapping, Sequence
from typing import Any, ClassVar

import numpy as np
import scipy.linalg

from .exceptions import LikelihoodError
from .hsgp import basis_size, check_spectral_support, normalise_counts
from .kernels import Kernel, _as_float64, _as_points
from .results_schema import FunctionSamples
from .likelihood import GPConditional, GPSolver, _components

__all__ = [
    "DEFAULT_GRID_SIZE",
    "EquispacedFourierGP",
    "FourierGrid",
    "fourier_grid",
    "real_features",
    "solve_iterative",
    "spectral_weights",
    "toeplitz_generator",
    "toeplitz_matrix",
    "toeplitz_matvec",
]

DTYPE = np.float64
CDTYPE = np.complex128

_LOG_2PI = math.log(2.0 * math.pi)

#: Grid points per axis when nothing says otherwise. Odd, and comparable with
#: :data:`~ampere.core.hsgp.DEFAULT_BASIS_SIZE`: HSGP's ``m`` members run over
#: positive frequencies to ``pi m / (2L)``, this grid's ``2M + 1`` run over
#: ``+-M pi / L``, so equal counts reach very nearly the same frequency.
DEFAULT_GRID_SIZE: int = 33

#: The box half-width as a multiple of the data's half-extent, as HSGP's.
DEFAULT_BOUNDARY_FACTOR: float = 2.0

#: Conjugate-gradient defaults for :func:`solve_iterative`. ``M >= I`` by
#: construction, so the system is never worse conditioned than ``K + D`` and a
#: few dozen iterations is generous.
DEFAULT_TOLERANCE: float = 1e-10
DEFAULT_MAX_ITERATIONS: int = 200


# ---------------------------------------------------------------------------
# The grid: a constant of the data, as HSGP's box is
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class FourierGrid:
    """Where the frequency grid is: spacing, extent, and the members themselves.

    Every field is a constant of the *data* and of the declaration — no fitted
    value enters — which is what keeps the representation a fixed linear one
    and the latent block a fixed size.

    Attributes
    ----------
    centre
        ``(d,)`` midpoint of the data's extent on each selected axis. Phases
        are evaluated on centred coordinates, so the aliasing period is
        measured about the middle of the data rather than about the origin.
    half_width
        ``(d,)`` :math:`L_k = c\\,S_k`, the data's half-extent scaled by the
        boundary factor.
    spacing
        ``(d,)`` :math:`h_k = \\pi / L_k`.
    counts
        Grid points per axis, odd. The total is their product.
    orders
        ``(m, d)`` integer index :math:`j_k \\in [-M_k, M_k]` of each member,
        in the C order every contraction here builds.
    frequencies
        ``(m, d)`` :math:`\\omega_{k} = h_k j_k`.
    norms
        ``(m,)`` :math:`\\|\\boldsymbol\\omega\\|`, the isotropic argument a
        spectral density is evaluated at.
    boundary_factor
        The multiple :attr:`half_width` came from, carried for provenance.
    """

    centre: np.ndarray
    half_width: np.ndarray
    spacing: np.ndarray
    counts: tuple[int, ...]
    orders: np.ndarray
    frequencies: np.ndarray
    norms: np.ndarray
    boundary_factor: float

    @property
    def size(self) -> int:
        """How many grid points there are: ``prod(counts)``."""
        return int(self.norms.shape[0])

    @property
    def dimensions(self) -> int:
        """How many axes the grid spans."""
        return len(self.counts)

    @property
    def cell_volume(self) -> float:
        """:math:`\\prod_k h_k`, the rectangle rule's weight."""
        return float(np.prod(self.spacing))


def normalise_grid_counts(declaration: int | Sequence[int]) -> tuple[int, ...]:
    """Read a ``basis_size`` declaration as a per-axis tuple of **odd** counts.

    Odd is not a convenience. The rectangle rule's grid is symmetric about
    zero — that is what makes :math:`K` real and the Toeplitz generator
    Hermitian — and an even count has no centre to be symmetric about.
    """
    counts = normalise_counts(declaration)
    even = [count for count in counts if count % 2 == 0]
    if even:
        raise LikelihoodError(
            f"EquispacedFourierGP's basis_size must be odd on every axis, got {counts!r}. The "
            f"frequency grid runs over -M..M and is symmetric about zero, which is what makes "
            f"the represented covariance real; an even count has no zero to be symmetric about. "
            f"Use {tuple(count + 1 for count in counts)!r}."
        )
    return counts


def fourier_grid(
    points: Any,
    counts: Sequence[int],
    boundary_factor: float = DEFAULT_BOUNDARY_FACTOR,
) -> FourierGrid:
    """The equispaced frequency grid for *points*, in numpy.

    Parameters
    ----------
    points
        ``(n, d)`` coordinates, already reduced to the axes the kernel
        selects. Read in numpy whatever namespace they arrive in: they are
        data.
    counts
        Grid points per axis, odd, one entry per column of *points*.
    boundary_factor
        :math:`c` in :math:`h_k = \\pi/(c S_k)`.

    Notes
    -----
    A degenerate axis — every sample at one coordinate — is given a unit
    half-extent, for :func:`~ampere.core.hsgp.hilbert_basis`'s reason: the
    kernel contributes nothing along an axis it cannot separate, and the
    failure belongs here rather than in the middle of a factorisation.
    """
    block = _as_points(points, "data coordinates")
    dimensions = int(block.shape[1])
    if len(counts) != dimensions:
        raise LikelihoodError(
            f"the equispaced Fourier grid was declared with {len(counts)} axis count(s) "
            f"{tuple(counts)!r} but the coordinates it is built on have {dimensions}."
        )
    if not math.isfinite(boundary_factor) or boundary_factor <= 0.0:
        raise LikelihoodError(
            f"EquispacedFourierGP's boundary_factor must be finite and > 0, got "
            f"{boundary_factor!r}."
        )
    lower = np.min(block, axis=0)
    upper = np.max(block, axis=0)
    centre = 0.5 * (lower + upper)
    extent = 0.5 * (upper - lower)
    extent = np.where(extent > 0.0, extent, 1.0)
    half_width = np.asarray(boundary_factor * extent, dtype=DTYPE)
    spacing = np.asarray(math.pi / half_width, dtype=DTYPE)

    per_axis = [np.arange(-(count // 2), count // 2 + 1, dtype=np.int64) for count in counts]
    grids = np.meshgrid(*per_axis, indexing="ij")
    orders = np.stack([grid.reshape(-1) for grid in grids], axis=-1)
    frequencies = np.asarray(orders, dtype=DTYPE) * spacing[None, :]
    norms = np.sqrt(np.sum(frequencies * frequencies, axis=-1))
    return FourierGrid(
        centre=np.asarray(centre, dtype=DTYPE),
        half_width=half_width,
        spacing=spacing,
        counts=tuple(int(count) for count in counts),
        orders=np.ascontiguousarray(orders),
        frequencies=np.ascontiguousarray(frequencies, dtype=DTYPE),
        norms=np.ascontiguousarray(norms, dtype=DTYPE),
        boundary_factor=float(boundary_factor),
    )


def spectral_weights(kernel: Kernel, grid: FourierGrid, values: Mapping[str, Any]) -> np.ndarray:
    """:math:`w_{\\mathbf j}`, the ``(m,)`` non-negative quadrature weights.

    The only hyperparameter-dependent piece, evaluated through the kernel's own
    :meth:`~ampere.core.kernels.Kernel.spectral_density` so that a fitted
    amplitude and length scale reach it from the one place the closed form
    lives.
    """
    density = np.asarray(
        kernel.spectral_density(grid.norms, values, dimensions=grid.dimensions), dtype=DTYPE
    )
    if not np.all(np.isfinite(density)) or np.any(density < 0.0):
        raise LikelihoodError(
            "the kernel's spectral density is not finite and non-negative at the grid "
            "frequencies, so the quadrature K ~ sum_j w_j exp(i omega_j . r) is not a "
            "covariance. The usual cause is a kernel amplitude or length scale outside its "
            "prior's support; a spectral density is non-negative for every admissible "
            "hyperparameter (Bochner)."
        )
    scale = grid.cell_volume / (2.0 * math.pi) ** grid.dimensions
    return np.asarray(density * scale, dtype=DTYPE)


# ---------------------------------------------------------------------------
# The separable contractions everything is built from
# ---------------------------------------------------------------------------


def _centred(grid: FourierGrid, points: np.ndarray) -> np.ndarray:
    """*points* about the grid's centre, ``(n, d)``."""
    return np.ascontiguousarray(points - grid.centre[None, :], dtype=DTYPE)


def _phases(grid: FourierGrid, centred: np.ndarray, axis: int, orders: np.ndarray) -> np.ndarray:
    """``(n, t)`` block of :math:`e^{i h_a j x_a}` for the integers *orders*."""
    argument = float(grid.spacing[axis]) * np.outer(centred[:, axis], orders.astype(DTYPE))
    return np.exp(1j * argument)


def _contract(weights: np.ndarray, factors: Sequence[np.ndarray]) -> np.ndarray:
    """:math:`\\sum_p w_p \\prod_a F_a[p, t_a]`, shaped ``(t_0, ..., t_{d-1})``.

    The one routine that gives EFGP its cost. Written as GEMMs rather than as
    an ``einsum`` over an ``(n, t_0, t_1)`` intermediate, because the whole
    point is never to allocate an ``N``-by-``m`` block: the one- and two-axis
    cases are a matrix-vector and a matrix-matrix product, and a third axis is
    a loop of two-axis contractions, so the peak allocation stays
    ``O(N max_a t_a)`` at every dimension.
    """
    if len(factors) == 1:
        return factors[0].T @ weights.astype(CDTYPE)
    if len(factors) == 2:
        return (factors[0] * weights[:, None]).T @ factors[1]
    head = factors[0]
    return np.stack(
        [_contract(weights * head[:, index], factors[1:]) for index in range(head.shape[1])],
        axis=0,
    )


def toeplitz_generator(grid: FourierGrid, points: np.ndarray, weights: np.ndarray) -> np.ndarray:
    """:math:`G[\\boldsymbol\\delta] = \\sum_p w_p e^{-i h \\boldsymbol\\delta \\cdot x_p}`.

    Shaped ``(2 n_0 - 1, ..., 2 n_{d-1} - 1)`` with :math:`\\boldsymbol\\delta
    = 0` at the centre of each axis: the generator of the Toeplitz normal
    matrix, and the array an FFT-based matvec embeds in a circulant.

    *weights* is :math:`1/D_p` for the normal matrix; a residual over the noise
    variance gives the right-hand side instead, on the smaller grid.
    """
    centred = _centred(grid, points)
    factors = [
        _phases(grid, centred, axis, -np.arange(-(count - 1), count, dtype=np.int64))
        for axis, count in enumerate(grid.counts)
    ]
    return np.asarray(_contract(np.asarray(weights, dtype=DTYPE), factors), dtype=CDTYPE)


def _projection(grid: FourierGrid, points: np.ndarray, weights: np.ndarray) -> np.ndarray:
    """:math:`\\sum_p w_p e^{-i\\boldsymbol\\omega_{\\mathbf j}\\cdot x_p}`, ``(m,)``.

    The unweighted half of :math:`\\tilde\\Phi^{\\mathsf H} D^{-1} r`, on the
    grid itself rather than on the difference grid.
    """
    centred = _centred(grid, points)
    factors = [
        _phases(grid, centred, axis, -np.arange(-(count // 2), count // 2 + 1, dtype=np.int64))
        for axis, count in enumerate(grid.counts)
    ]
    block = _contract(np.asarray(weights, dtype=DTYPE), factors)
    return np.asarray(block, dtype=CDTYPE).reshape(-1)


def toeplitz_matrix(grid: FourierGrid, generator: np.ndarray) -> np.ndarray:
    """The dense ``(m, m)`` (block-)Toeplitz matrix *generator* generates.

    Formed explicitly because the solver factorises it: a Cholesky needs the
    matrix, and :math:`O(m^2)` storage is small beside the :math:`O(N m)` block
    the method exists to avoid. :func:`toeplitz_matvec` is the route that never
    forms it.
    """
    counts = np.asarray(grid.counts, dtype=np.int64)
    indices = grid.orders + (counts - 1) // 2  # 0-based multi-index of each member
    difference = indices[:, None, :] - indices[None, :, :] + (counts - 1)[None, None, :]
    return np.asarray(generator[tuple(difference[..., axis] for axis in range(len(grid.counts)))])


def toeplitz_matvec(grid: FourierGrid, generator: np.ndarray, vector: np.ndarray) -> np.ndarray:
    """The Toeplitz product :math:`T v`, by circulant embedding and FFT.

    :math:`O(m \\log m)` per call, with no ``(m, m)`` matrix anywhere. This is
    the operation Greengard et al.'s :math:`O(N + m \\log m)` claim rests on,
    and :func:`solve_iterative` is what it buys; the log-determinant a marginal
    likelihood also needs is what it does not (see the module docstring).
    """
    counts = grid.counts
    padded = tuple(2 * count - 1 for count in counts)
    # The circulant's first column: position ``i`` on an axis stands for the
    # index difference ``i`` while ``i < n`` and for ``i - (2n - 1)``, a
    # negative difference, after it. Every axis wraps **independently**, so the
    # map is built per axis and taken as an outer index — a 2-D embedding has
    # four corners, not two, and filling only the two that a 1-D one has is
    # the mistake this comment exists to prevent recurring.
    maps = []
    for count in counts:
        positions = np.arange(2 * count - 1)
        difference = np.where(positions < count, positions, positions - (2 * count - 1))
        maps.append(difference + (count - 1))
    embedded = np.asarray(generator[np.ix_(*maps)], dtype=CDTYPE)
    forward = tuple(slice(0, count) for count in counts)
    block = np.zeros(padded, dtype=CDTYPE)
    block[forward] = np.reshape(vector, counts)
    product = np.fft.ifftn(np.fft.fftn(embedded) * np.fft.fftn(block))
    return np.asarray(product[forward].reshape(-1), dtype=CDTYPE)


def solve_iterative(
    grid: FourierGrid,
    generator: np.ndarray,
    root_weights: np.ndarray,
    right: np.ndarray,
    *,
    tolerance: float = DEFAULT_TOLERANCE,
    max_iterations: int = DEFAULT_MAX_ITERATIONS,
) -> tuple[np.ndarray, int]:
    """:math:`M^{-1} b` by conjugate gradients on FFT matvecs, and the iteration count.

    :math:`M = I_m + \\operatorname{diag}(\\sqrt w)\\,T\\,\\operatorname{diag}
    (\\sqrt w)` is Hermitian and :math:`\\succeq I`, so CG converges on it
    unconditionally and quickly. Supplied for the W5.6 bake-off rather than
    used by :class:`EquispacedFourierGP`, which needs :math:`\\log|M|` and so
    factorises instead; the two are measured side by side so the table can say
    what the iterative route removes and what it does not.
    """
    iterations = 0

    def apply(vector: np.ndarray) -> np.ndarray:
        nonlocal iterations
        iterations += 1
        scaled = root_weights.astype(CDTYPE) * vector
        return vector + root_weights.astype(CDTYPE) * toeplitz_matvec(grid, generator, scaled)

    target = np.asarray(right, dtype=CDTYPE)
    solution = np.zeros_like(target)
    residual = target - apply(solution)
    direction = residual.copy()
    squared = float(np.real(np.vdot(residual, residual)))
    goal = tolerance * tolerance * float(np.real(np.vdot(target, target)))
    for _ in range(max_iterations):
        if squared <= goal:
            break
        applied = apply(direction)
        step = squared / float(np.real(np.vdot(direction, applied)))
        solution = solution + step * direction
        residual = residual - step * applied
        updated = float(np.real(np.vdot(residual, residual)))
        direction = residual + (updated / squared) * direction
        squared = updated
    return solution, iterations


def real_features(grid: FourierGrid, weights: np.ndarray, points: np.ndarray) -> np.ndarray:
    """A **real** ``(n, m)`` factor :math:`\\Psi` with :math:`\\Psi\\Psi^{\\mathsf T} = K`.

    The complex representation is what makes the normal matrix Toeplitz, and it
    is the wrong one for :meth:`~ampere.core.GPSolver.latent_transform`, which
    must map real whitened draws to a real GP draw. Pairing
    :math:`\\boldsymbol\\omega` with :math:`-\\boldsymbol\\omega` — which the
    symmetric grid always can, and which an even count could not — turns the
    sum into

    .. math::
        K(\\mathbf r) = w_{\\mathbf 0}
        + \\sum_{\\text{pairs}} 2 w_{\\mathbf j}\\cos(\\boldsymbol\\omega_{\\mathbf j}
          \\cdot \\mathbf r) ,

    and a cosine of a difference splits into
    :math:`\\cos\\cos + \\sin\\sin`. So each conjugate pair contributes two
    real columns and the zero frequency one: exactly ``m`` of them, which is
    why the latent block is the same size in either representation.
    """
    centred = _centred(grid, points)
    argument = centred @ grid.frequencies.T  # (n, m)
    orders = grid.orders
    leading = np.zeros(orders.shape[0], dtype=np.int64)
    nonzero = orders != 0
    first = np.argmax(nonzero, axis=1)
    has_any = np.any(nonzero, axis=1)
    leading[has_any] = orders[np.arange(orders.shape[0])[has_any], first[has_any]]
    positive = leading > 0
    zero = ~has_any
    columns = [np.sqrt(weights[zero])[None, :] * np.ones((centred.shape[0], int(np.sum(zero))))]
    root = np.sqrt(2.0 * weights[positive])[None, :]
    columns.append(root * np.cos(argument[:, positive]))
    columns.append(root * np.sin(argument[:, positive]))
    return np.ascontiguousarray(np.concatenate(columns, axis=1), dtype=DTYPE)


# ---------------------------------------------------------------------------
# The solver
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class EquispacedFourierGP(GPSolver):
    """Approximate GP algebra on an equispaced Fourier grid (**W5.6 prototype**).

    A ``EXACT = False`` solver in :class:`~ampere.core.HilbertSpaceGP`'s
    comparison class — the conformance suite's ``approximation_order`` /
    ``approximation_floor`` / ``approximation_final`` envelope
    (``tests/conformance/README.md`` §3), because the error falls as the grid
    is refined and floors at the periodisation the spacing fixes, which is the
    same two-parameter statement HSGP makes about its box.

    **This is a measurement prototype, and the reference path only.** W5.6's
    item is a bake-off whose *outcome* is a decision-log row naming which of
    EFGP and Vecchia is promoted to a full three-backend solver; until that
    row is acted on there is no torch or jax twin, so a problem composed with
    this solver is a numpy problem (``DIFFERENTIABLE`` and ``BATCHABLE`` stay
    false, and the capability ladder refuses it on a native backend, which is
    the loud behaviour W2.13 exists to give).

    Parameters
    ----------
    basis_size
        Grid points **per axis**, odd; the total ``m`` is their product. Named
        to match :class:`~ampere.core.HilbertSpaceGP`'s field so the two are
        declared, hashed and read the same way.
    boundary_factor
        The spacing, as :math:`h_k = \\pi/(c S_k)`; see the module docstring
        for why it is the same statement as HSGP's box factor.
    jitter
        A standard deviation added in quadrature to the noise diagonal, the
        same knob, meaning and default as :class:`~ampere.core.DenseGP`'s.

    Examples
    --------
    >>> from ampere.core import Matern32
    >>> solver = EquispacedFourierGP(basis_size=33, boundary_factor=2.0)
    >>> solver.counts
    (33,)
    >>> solver.latent_size(Matern32(0.3, 2.0), 500)
    33
    >>> EquispacedFourierGP(basis_size=(17, 17)).provenance_config()
    {'basis_size': [17, 17], 'boundary_factor': 2.0}
    """

    basis_size: int | tuple[int, ...] = DEFAULT_GRID_SIZE
    boundary_factor: float = DEFAULT_BOUNDARY_FACTOR
    jitter: float = 0.0

    NAME: ClassVar[str] = "EquispacedFourierGP"
    EXACT: ClassVar[bool] = False
    IMPLEMENTED: ClassVar[bool] = True
    #: Woodbury takes extra columns exactly as the dense Cholesky does: one
    #: factorisation of ``M``, ``k`` solves, the log-determinant counted ``k``
    #: times.
    STACKED_RESIDUALS: ClassVar[bool] = True

    def __post_init__(self) -> None:
        object.__setattr__(self, "basis_size", normalise_grid_counts(self.basis_size))
        if not math.isfinite(self.boundary_factor) or self.boundary_factor <= 0.0:
            raise LikelihoodError(
                f"EquispacedFourierGP's boundary_factor must be finite and > 0, got "
                f"{self.boundary_factor!r}. It fixes the grid spacing h = pi / (c S), and the "
                f"quadrature's error is the periodisation of the kernel at period 2 c S, so it "
                f"must be at least 1 for the period to cover the data at all."
            )
        if not math.isfinite(self.jitter) or self.jitter < 0.0:
            raise LikelihoodError(
                f"EquispacedFourierGP's jitter must be finite and >= 0, got {self.jitter!r}."
            )

    @property
    def counts(self) -> tuple[int, ...]:
        """Grid points per axis, normalised to a tuple."""
        return normalise_grid_counts(self.basis_size)

    def provenance_config(self) -> Mapping[str, Any]:
        """The approximation, for the run's attrs — as HSGP's, for its reason."""
        return {
            "basis_size": [int(count) for count in self.counts],
            "boundary_factor": float(self.boundary_factor),
        }

    def latent_size(self, kernel: Kernel, n_samples: int) -> int:
        """``m``, not ``N``: the grid's size, from the declaration alone."""
        del kernel, n_samples
        return basis_size(self.counts)

    def check_compatible(self, kernel: Kernel, observed: FunctionSamples) -> None:
        """The layout and axis rules, plus a spectral density and a matching count."""
        super().check_compatible(kernel, observed)
        selected = kernel.selected_axes([axis.name for axis in observed.axes])
        dimensions = len(selected)
        check_spectral_support(kernel, dimensions, owner=self.NAME)
        counts = self.counts
        if len(counts) != dimensions:
            raise LikelihoodError(
                f"{self.NAME} was declared with basis_size={self.basis_size!r} — "
                f"{len(counts)} axis count(s) — but the kernel selects {dimensions} axis/axes "
                f"{selected!r} of this {type(observed).__name__}. The grid is a tensor product "
                f"with one count per axis, and the total m is their product, so the two must "
                f"agree: pass basis_size={tuple([counts[0]] * dimensions)!r} for the same "
                f"resolution on each."
            )

    # -- internals -----------------------------------------------------------

    def _grid(self, kernel: Kernel, points: np.ndarray) -> FourierGrid:
        return fourier_grid(kernel.select(points), self.counts, self.boundary_factor)

    def _diagonal(self, variance: np.ndarray) -> np.ndarray:
        diagonal = _as_float64(variance, "noise variances") + self.jitter**2
        if not np.all(np.isfinite(diagonal)) or np.any(diagonal <= 0.0):
            raise LikelihoodError(
                f"{self.NAME} needs a strictly positive noise diagonal: the Woodbury identity it "
                f"solves by inverts diag(sigma^2 + jitter^2) directly, so a zero uncertainty is "
                f"a division by zero rather than an ill-conditioned matrix. Pass "
                f"{self.NAME}(jitter=...) — a standard deviation in the data's units — or use "
                f"DenseGP, whose Cholesky needs only K + diag(sigma^2) to be positive definite."
            )
        return diagonal

    def _normal_factor(
        self,
        grid: FourierGrid,
        points: np.ndarray,
        weights: np.ndarray,
        diagonal: np.ndarray,
    ) -> tuple[np.ndarray, tuple[np.ndarray, bool]]:
        """``(sqrt(w), cho_factor(M))`` — the one factorisation everything uses."""
        generator = toeplitz_generator(grid, points, 1.0 / diagonal)
        root = np.sqrt(weights)
        matrix = toeplitz_matrix(grid, generator)
        matrix = matrix * root[:, None] * root[None, :]
        matrix[np.diag_indices_from(matrix)] += 1.0
        try:
            factor = scipy.linalg.cho_factor(matrix, lower=True)
        except scipy.linalg.LinAlgError as error:
            raise LikelihoodError(
                f"the equispaced-Fourier normal matrix I + Phi^H D^-1 Phi is not positive "
                f"definite, so the Woodbury solve failed ({error}). It is positive definite for "
                f"every admissible hyperparameter, so this is a numerical rather than a "
                f"structural failure: reduce basis_size, or raise the jitter."
            ) from error
        return root, factor

    def _right_hand_side(
        self,
        grid: FourierGrid,
        points: np.ndarray,
        root: np.ndarray,
        residuals: np.ndarray,
        diagonal: np.ndarray,
    ) -> np.ndarray:
        """:math:`\\tilde\\Phi^{\\mathsf H} D^{-1} r`, ``(m,)`` or ``(m, k)``."""
        if residuals.ndim == 1:
            return root * _projection(grid, points, residuals / diagonal)
        return np.stack(
            [
                root * _projection(grid, points, residuals[:, column] / diagonal)
                for column in range(residuals.shape[1])
            ],
            axis=-1,
        )

    def _features(self, grid: FourierGrid, root: np.ndarray, points: np.ndarray) -> np.ndarray:
        """:math:`\\tilde\\Phi` at *points*, ``(n, m)`` complex.

        Formed only where a per-sample quantity needs it — the leave-one-out
        terms and the conditional variance — never in the marginal likelihood,
        which is the whole reason the method is cheap. Callers chunk.
        """
        centred = _centred(grid, points)
        rows = int(centred.shape[0])
        block = np.ones((rows, 1), dtype=CDTYPE)
        for axis, count in enumerate(grid.counts):
            wave = _phases(
                grid, centred, axis, np.arange(-(count // 2), count // 2 + 1, dtype=np.int64)
            )
            block = (block[:, :, None] * wave[:, None, :]).reshape(rows, -1)
        return np.asarray(block * root[None, :], dtype=CDTYPE)

    def _chunk(self, size: int, columns: int) -> int:
        """Rows per chunk, so a per-sample pass stays inside ~64 MiB."""
        budget = 64 * 1024 * 1024 // (16 * max(columns, 1))
        return max(1, min(size, int(budget)))

    # -- the interface -------------------------------------------------------

    def log_marginal_likelihood(
        self,
        kernel: Kernel,
        coordinates: np.ndarray,
        residual: np.ndarray,
        variance: np.ndarray,
        values: Mapping[str, Any],
    ) -> float:
        """The marginal likelihood **of the quadrature**, summed over the columns.

        Not of the declared kernel: :attr:`EXACT` is ``False`` and this is what
        that means. It is the exact marginal likelihood of the rank-``m``
        process :math:`\\tilde\\Phi\\tilde\\Phi^{\\mathsf H}`, which converges
        to the declared one as the grid is refined in both its parameters.
        """
        points = _as_points(coordinates, "data coordinates")
        residuals = _as_float64(residual, "residuals")
        grid = self._grid(kernel, points)
        selected = kernel.select(points)
        weights = spectral_weights(kernel, grid, values)
        diagonal = self._diagonal(variance)
        root, factor = self._normal_factor(grid, selected, weights, diagonal)
        projected = self._right_hand_side(grid, selected, root, residuals, diagonal)
        log_determinant = float(np.sum(np.log(diagonal))) + 2.0 * float(
            np.sum(np.log(np.abs(np.diag(factor[0]))))
        )
        direct = float(
            np.sum(residuals * residuals / (diagonal if residuals.ndim == 1 else diagonal[:, None]))
        )
        corrected = float(np.real(np.vdot(projected, scipy.linalg.cho_solve(factor, projected))))
        columns = _components(residuals)
        return -0.5 * (direct - corrected + columns * log_determinant + residuals.size * _LOG_2PI)

    def conditional_loo(
        self,
        kernel: Kernel,
        coordinates: np.ndarray,
        residual: np.ndarray,
        variance: np.ndarray,
        values: Mapping[str, Any],
    ) -> np.ndarray:
        """Sundararajan & Keerthi's identity, exact in the quadrature.

        Woodbury gives :math:`(A^{-1})_{ii}` in closed form without forming
        :math:`A`, exactly as :class:`~ampere.core.HilbertSpaceGP`'s does —
        but it needs the rows of :math:`\\tilde\\Phi`, so this is the one
        quantity that costs :math:`O(N m^2)` and the one place EFGP has no
        advantage over HSGP. It is chunked rather than refused because the
        arithmetic is sound; the cost is recorded in ``likelihoods.md`` §7.
        """
        points = _as_points(coordinates, "data coordinates")
        residuals = _as_float64(residual, "residuals")
        grid = self._grid(kernel, points)
        selected = kernel.select(points)
        weights = spectral_weights(kernel, grid, values)
        diagonal = self._diagonal(variance)
        root, factor = self._normal_factor(grid, selected, weights, diagonal)
        projected = self._right_hand_side(grid, selected, root, residuals, diagonal)
        correction = scipy.linalg.cho_solve(factor, projected)

        rows = int(residuals.shape[0])
        columns = _components(residuals)
        divisor = diagonal if residuals.ndim == 1 else diagonal[:, None]
        alpha = residuals / divisor
        precision = 1.0 / diagonal
        step = self._chunk(rows, grid.size)
        for start in range(0, rows, step):
            stop = min(start + step, rows)
            block = self._features(grid, root, selected[start:stop])
            alpha[start:stop] -= np.real(block @ correction) / divisor[start:stop]
            triangular = scipy.linalg.solve_triangular(
                factor[0], (block / diagonal[start:stop, None]).conj().T, lower=True
            )
            precision[start:stop] -= np.sum(np.abs(triangular) ** 2, axis=0)
        quadratic = np.sum(np.reshape(alpha, (rows, columns)) ** 2, axis=1)
        return np.asarray(
            columns * (0.5 * np.log(precision) - 0.5 * _LOG_2PI) - quadratic / (2.0 * precision),
            dtype=DTYPE,
        )

    def condition(
        self,
        kernel: Kernel,
        coordinates: np.ndarray,
        residual: np.ndarray,
        variance: np.ndarray,
        values: Mapping[str, Any],
        at: np.ndarray | None = None,
    ) -> GPConditional:
        """The posterior of the rank-``m`` process, at ``at`` or at the data.

        The prior variance is the **quadrature's**, for
        :class:`~ampere.core.HilbertSpaceGP`'s reason: mixing an exact prior
        with an approximate correction gives a variance that is the variance of
        nothing and can go negative. Taken consistently the posterior variance
        is :math:`\\|L_M^{-1}\\tilde\\Phi_*^{\\mathsf H}\\|^2`, non-negative at
        every ``m``.
        """
        points = _as_points(coordinates, "data coordinates")
        residuals = _as_float64(residual, "residuals")
        grid = self._grid(kernel, points)
        selected = kernel.select(points)
        weights = spectral_weights(kernel, grid, values)
        diagonal = self._diagonal(variance)
        root, factor = self._normal_factor(grid, selected, weights, diagonal)
        projected = self._right_hand_side(grid, selected, root, residuals, diagonal)
        # tilde-Phi^H alpha, with alpha = (K + D)^-1 r, entirely on the grid.
        coefficients = projected - (
            self._normal_projection(grid, selected, root, diagonal, projected, factor)
        )
        if at is None:
            target = selected
        else:
            target = kernel.select(_as_points(at, "conditioning grid", dimensions=points.shape[1]))
        target = np.ascontiguousarray(target, dtype=DTYPE)
        rows = int(target.shape[0])
        columns = _components(residuals)
        mean = np.zeros((rows, columns), dtype=DTYPE) if residuals.ndim != 1 else np.zeros(rows)
        posterior = np.zeros(rows, dtype=DTYPE)
        step = self._chunk(rows, grid.size)
        for start in range(0, rows, step):
            stop = min(start + step, rows)
            block = self._features(grid, root, target[start:stop])
            mean[start:stop] = np.real(block @ coefficients)
            triangular = scipy.linalg.solve_triangular(factor[0], block.conj().T, lower=True)
            posterior[start:stop] = np.sum(np.abs(triangular) ** 2, axis=0)
        return GPConditional(mean=mean, variance=posterior)

    def _normal_projection(
        self,
        grid: FourierGrid,
        points: np.ndarray,
        root: np.ndarray,
        diagonal: np.ndarray,
        projected: np.ndarray,
        factor: tuple[np.ndarray, bool],
    ) -> np.ndarray:
        """:math:`C M^{-1} \\tilde\\Phi^{\\mathsf H} D^{-1} r`, with ``C = M - I``.

        The identity that keeps :meth:`condition` off the ``(N, m)`` block for
        its *mean*: :math:`\\tilde\\Phi^{\\mathsf H}(K+D)^{-1} r = (I -
        C M^{-1}) \\tilde\\Phi^{\\mathsf H} D^{-1} r` with
        :math:`C = \\tilde\\Phi^{\\mathsf H} D^{-1}\\tilde\\Phi`, and ``C``
        applies by FFT.
        """
        generator = toeplitz_generator(grid, points, 1.0 / diagonal)
        solved = scipy.linalg.cho_solve(factor, projected)
        if solved.ndim == 1:
            return root * toeplitz_matvec(grid, generator, root * solved)
        return np.stack(
            [
                root * toeplitz_matvec(grid, generator, root * solved[:, column])
                for column in range(solved.shape[1])
            ],
            axis=-1,
        )

    def latent_transform(
        self,
        kernel: Kernel,
        coordinates: np.ndarray,
        whitened: np.ndarray,
        values: Mapping[str, Any],
        *,
        jitter: float = 1e-10,
    ) -> np.ndarray:
        """``f = Psi z`` — the real cosine/sine whitening, from ``m`` variables.

        The complex grid and the real feature pair represent the *same*
        covariance (:func:`real_features`), so this is the same approximation
        the marginal likelihood scores; the stabilising ``jitter`` is accepted
        and unused, because :math:`\\Psi\\Psi^{\\mathsf T}` is positive
        semi-definite by construction with no factorisation to stabilise.
        """
        del jitter
        points = _as_points(coordinates, "data coordinates")
        draws = _as_float64(whitened, "whitened latent draws")
        grid = self._grid(kernel, points)
        weights = spectral_weights(kernel, grid, values)
        if np.shape(draws)[0] != grid.size:
            raise LikelihoodError(
                f"{self.NAME} whitens {grid.size} Fourier coefficient(s), but it was handed "
                f"{np.shape(draws)[0]} whitened value(s). This solver's latent block is the "
                f"grid size m, not the sample count — see GPSolver.latent_size."
            )
        return real_features(grid, weights, kernel.select(points)) @ draws
